### ISSUE TITLE
[기능정의서] 호스트의 등록 기능

### ISSUE THREAD

**Issue by red-dev-Mark** [red-dev-Mark/devcamp-onboarding-project-Team-2#21]
1. 기능정의서의 **호스트의 등록 기능**에 대한 상세 내용 작성
2. 해당 기능의 플로우차트 및 다이어그램 작성

담당: 송병훈

**Comment by sbs1253** [comment]
호스트 회원가입,
호스트 인증,
호스트 등록 => 호스트 숙소등록 으로 수정
3가지로 분류

**Comment by sbs1253** [comment]
플로우 차트 작성

**Comment by sbs1253** [comment]
수정 사항 확인 및 추가자료 검토
